//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReviewService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApprovalProcessType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ApprovalProcessType()
        {
            this.GroupRoleRelations = new HashSet<GroupRoleRelation>();
        }
    
        public int ApprovalProcessId { get; set; }
        public Nullable<int> StartNodeId { get; set; }
        public string ApprovalType { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public Nullable<int> FunctionId { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<int> RegionId { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual CorpFunction CorpFunction { get; set; }
        public virtual Node Node { get; set; }
        public virtual Product Product { get; set; }
        public virtual Region Region { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GroupRoleRelation> GroupRoleRelations { get; set; }
    }
}
