//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReviewService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Audit_Log
    {
        public int AuditId { get; set; }
        public int PersonId { get; set; }
        public Nullable<int> DelegateId { get; set; }
        public string TableName { get; set; }
        public string ColumnName { get; set; }
        public string AuditedAction { get; set; }
        public string AuditCriteria { get; set; }
    }
}
