//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReviewService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BranchNode
    {
        public int GuardId { get; set; }
        public int NodeId { get; set; }
        public Nullable<int> OutputNodeId { get; set; }
        public int ConditionId { get; set; }
        public int RelationTypeId { get; set; }
        public string Type { get; set; }
        public Nullable<int> AccessType { get; set; }
    
        public virtual BranchCondition BranchCondition { get; set; }
        public virtual Node Node { get; set; }
        public virtual Node Node1 { get; set; }
    }
}
