//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReviewService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupRoleRelation
    {
        public int GroupRelationId { get; set; }
        public Nullable<int> MasterGroupId { get; set; }
        public Nullable<int> RelativeGroupId { get; set; }
        public Nullable<System.DateTime> DateUpdated { get; set; }
        public Nullable<int> Enabled { get; set; }
        public int RelationTypeId { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> ApprovalProcessId { get; set; }
        public Nullable<int> GroupRoleWeight { get; set; }
    
        public virtual ApprovalProcessType ApprovalProcessType { get; set; }
        public virtual RelationType RelationType { get; set; }
        public virtual SysGroup SysGroup { get; set; }
        public virtual SysGroup SysGroup1 { get; set; }
    }
}
