//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReviewService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ITSystem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ITSystem()
        {
            this.SystemUsers = new HashSet<SystemUser>();
        }
    
        public int SystemId { get; set; }
        public string SystemName { get; set; }
        public string SystemEndpoint { get; set; }
        public string URL { get; set; }
        public string RedirectURL { get; set; }
        public string SystemHash { get; set; }
        public string SystemToken { get; set; }
        public string SystemSharedSecret { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SystemUser> SystemUsers { get; set; }
    }
}
