//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReviewService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RelationType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RelationType()
        {
            this.GroupRoleRelations = new HashSet<GroupRoleRelation>();
            this.RelationType1 = new HashSet<RelationType>();
        }
    
        public int RelationTypeId { get; set; }
        public string RelationDescription { get; set; }
        public Nullable<int> Recursive { get; set; }
        public Nullable<int> NumberofRecursions { get; set; }
        public Nullable<int> InverseRelationTypeId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GroupRoleRelation> GroupRoleRelations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RelationType> RelationType1 { get; set; }
        public virtual RelationType RelationType2 { get; set; }
    }
}
