//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReviewService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReviewTask
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ReviewTask()
        {
            this.DelegateTaskAssignments = new HashSet<DelegateTaskAssignment>();
            this.TaskAssignments = new HashSet<TaskAssignment>();
            this.TaskAssignmentHistories = new HashSet<TaskAssignmentHistory>();
            this.TaskNodes = new HashSet<TaskNode>();
        }
    
        public int TaskId { get; set; }
        public Nullable<System.DateTime> DateUpdated { get; set; }
        public string Status { get; set; }
        public Nullable<int> RaiserUserId { get; set; }
        public Nullable<int> ApprovalProcessType { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DelegateTaskAssignment> DelegateTaskAssignments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaskAssignment> TaskAssignments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaskAssignmentHistory> TaskAssignmentHistories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaskNode> TaskNodes { get; set; }
    }
}
