//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReviewService.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ReviewProjectEntities2 : DbContext
    {
        public ReviewProjectEntities2()
            : base("name=ReviewProjectEntities2")
        {
            base.Configuration.ProxyCreationEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AccessType> AccessTypes { get; set; }
        public virtual DbSet<ApprovalProcessType> ApprovalProcessTypes { get; set; }
        public virtual DbSet<Audit_Log> Audit_Log { get; set; }
        public virtual DbSet<AuditDefinition> AuditDefinitions { get; set; }
        public virtual DbSet<BranchCondition> BranchConditions { get; set; }
        public virtual DbSet<BranchNode> BranchNodes { get; set; }
        public virtual DbSet<Company> Companies { get; set; }
        public virtual DbSet<CorpFunction> CorpFunctions { get; set; }
        public virtual DbSet<DelegateTaskAssignment> DelegateTaskAssignments { get; set; }
        public virtual DbSet<GroupRoleRelation> GroupRoleRelations { get; set; }
        public virtual DbSet<ITSystem> ITSystems { get; set; }
        public virtual DbSet<Node> Nodes { get; set; }
        public virtual DbSet<PersonDelegate> PersonDelegates { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<Region> Regions { get; set; }
        public virtual DbSet<RelationType> RelationTypes { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<SysGroup> SysGroups { get; set; }
        public virtual DbSet<SystemUser> SystemUsers { get; set; }
        public virtual DbSet<ReviewTask> ReviewTasks { get; set; }
        public virtual DbSet<TaskAssignment> TaskAssignments { get; set; }
        public virtual DbSet<TaskAssignmentHistory> TaskAssignmentHistories { get; set; }
        public virtual DbSet<TaskNode> TaskNodes { get; set; }
        public virtual DbSet<UserGroup> UserGroups { get; set; }
        public virtual DbSet<UserPwdHistory> UserPwdHistories { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
