//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReviewService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SysGroup
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SysGroup()
        {
            this.GroupRoleRelations = new HashSet<GroupRoleRelation>();
            this.GroupRoleRelations1 = new HashSet<GroupRoleRelation>();
            this.TaskAssignments = new HashSet<TaskAssignment>();
            this.TaskAssignmentHistories = new HashSet<TaskAssignmentHistory>();
            this.UserGroups = new HashSet<UserGroup>();
        }
    
        public int GroupId { get; set; }
        public string GroupName { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public Nullable<int> FunctionId { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<int> RegionId { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual CorpFunction CorpFunction { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GroupRoleRelation> GroupRoleRelations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GroupRoleRelation> GroupRoleRelations1 { get; set; }
        public virtual Product Product { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaskAssignment> TaskAssignments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaskAssignmentHistory> TaskAssignmentHistories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserGroup> UserGroups { get; set; }
    }
}
