//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReviewService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemUser
    {
        public int SystemId { get; set; }
        public int PersonId { get; set; }
        public string SystemUserIdentifier { get; set; }
        public string SystemUserPassword { get; set; }
        public string SystemHash { get; set; }
        public string SystemSharedSecret { get; set; }
    
        public virtual ITSystem ITSystem { get; set; }
        public virtual User User { get; set; }
    }
}
