//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReviewService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskAssignment
    {
        public int TaskId { get; set; }
        public Nullable<System.DateTime> DateAssigned { get; set; }
        public int GroupId { get; set; }
        public string AccessType { get; set; }
        public Nullable<int> NodeId { get; set; }
    
        public virtual SysGroup SysGroup { get; set; }
        public virtual ReviewTask Task { get; set; }
    }
}
